import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local"; // Import the local font function
import "./globals.css";

// Load custom fonts
const JanatLT = localFont({ src: "../fonts/alfont_com_AAJannatLT-.ttf", display: "swap" });
const JanatWT = localFont({ src: "../fonts/alfont_com_خط-جنات-عريض.ttf", display: "swap" });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body>{children}</body>
    </html>
  );
}
